[project]
authors = ["Julian Hofer <julianhofer@gnome.org>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "rust_cache_test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.81.0,<2"
