[project]
authors = ["Julian Hofer <julianhofer@gnome.org>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "rust_cache_test"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]
build = "cargo build"
start = "cargo run"

[dependencies]
rust = ">=1.81.0,<2"
compilers = ">=1.8.0,<2"
make = ">=4.4.1,<5"

[target.linux-64.dependencies]
mold = ">=2.34.1,<3"
clang = ">=19.1.2,<20"

[target.linux-64.activation]
scripts = ["scripts/activate.sh"]
